### ISSUE TITLE
assembly failure for *!

### ISSUE THREAD

**Issue by helena-shapton** [kew-myco/its_glue#10]
Re email: New folder successfully created in output folder. Any recommendations to make work?
![image](https://user-images.githubusercontent.com/66360941/163367151-bfd64aa4-5c5f-4bb0-aea1-015969110288.png)

**Comment by blex-max** [comment]
Hello,
Are there no logs in the log folder? They would be useful. Also please show me an example of the trace file names.

**Comment by helena-shapton** [comment]
![image](https://user-images.githubusercontent.com/66360941/163386541-2f75c6cb-4e31-4539-b63d-36ce6372895a.png)

**Comment by blex-max** [comment]
Please could you upload cons_log.txt? The log files will often tell you what the problem is and are necessary for me to be able to help!

Also make sure you've done git pull to update to the latest version of the pipeline

**Comment by helena-shapton** [comment]
![image](https://user-images.githubusercontent.com/66360941/163388304-7bbb1530-eafb-47eb-9b2d-d13a5045a6e1.png)

**Comment by helena-shapton** [comment]
also i tried to update the pipeline and go this.. fatal: not a git repository (or any of the parent directories): .git

**Comment by blex-max** [comment]
The git error means you are not in the top level directory of the pipeline - you probably need to be in the folder its_glue and not in a subdirectory

**Comment by blex-max** [comment]
OK, so I suspect this error is occurring because you have made the tag in the filename the same as the flag the program uses to indicate the tag - i.e. you are trying to pass the argument '-f' to the flag -f.  Since the argument is not quoted, BASH (the language this program is written in) interprets -f -f as passing the -f flag twice. If you really want to name the files this way, try -f '-f'. In general I strongly advise preferring underscores to dashes in filenames

**Comment by blex-max** [comment]
@helena-shapton by the way, let me know if this solves your issue!

**Comment by helena-shapton** [comment]
Yes issue solved it ran the sequence alignment but it had a little issue at the end? 
![image](https://user-images.githubusercontent.com/66360941/163552468-eb7ce333-e84c-4c77-bc3e-b965248bd59b.png)

**Comment by blex-max** [comment]
Since the original issue has been solved, please open a new issue since this is a new problem - it will help me fix/help reliably. When you do, please upload the output of all logs (you can put them in a zip and attach them to the issue I think). There is now a bug/help template for submitting issues also which should come up when you open a new one.
